export const RESTAURANT_INFO = {
  name: "AACHARYA CAFE",
  tagline: "Authentic South Indian Flavours in the Heart of Jayanagar",
  description: "Experience the finest South Indian cuisine in Bangalore. From crispy dosas to aromatic filter coffee, we serve authentic flavors that remind you of home.",
  category: "South Indian Restaurant",
  address: {
    street: "493/K, Krishna Rajendra Rd, 7th Block",
    area: "Jayanagar",
    city: "Bengaluru",
    state: "Karnataka",
    pincode: "560070",
    landmark: "Opposite HDFC Bank",
    full: "493/K, Krishna Rajendra Rd, 7th Block, Jayanagar, Bengaluru, Karnataka 560070",
  },
  contact: {
    phone: "+91 90199 36889",
    displayPhone: "+91 90199 36889",
    whatsapp: "919019936889",
  },
  hours: {
    open: "6:00 AM",
    close: "1:00 AM",
    display: "6:00 AM – 1:00 AM",
  },
  pricing: {
    min: 1,
    max: 200,
    currency: "₹",
    display: "₹1–200 per person",
  },
  rating: {
    value: 4.1,
    count: 203,
    max: 5,
  },
  services: ["Dine-in", "Drive-through", "No-contact delivery"],
  links: {
    swiggy: "https://www.swiggy.com/direct/brand/741309?source=swiggy-direct&subSource=google",
    googleMaps: "https://maps.google.com/?q=493/K,Krishna+Rajendra+Rd,7th+Block,Jayanagar,Bengaluru,Karnataka+560070",
  },
  coordinates: {
    lat: 12.9352,
    lng: 77.5848,
  },
};

export const MENU_ITEMS = {
  idli: [
    {
      id: "1",
      name: "Thatte Idly",
      description: "Soft plate idlis served with sambar and chutney",
      price: 25,
      isVeg: true,
      isPopular: true,
      image: "/images/food/thatte-idly.jpg",
    },
    {
      id: "2",
      name: "Butter Thatte Idly",
      description: "Plate idlis topped with butter",
      price: 35,
      isVeg: true,
      image: "/images/food/butter-thatte-idly.jpg",
    },
    {
      id: "3",
      name: "Ghee Pudi Thatte Idly",
      description: "Plate idlis tossed in ghee and spicy podi",
      price: 40,
      isVeg: true,
      isPopular: true,
      image: "/images/food/ghee-pudi-thatte-idly.jpg",
    },
    {
      id: "4",
      name: "Ghee Idly",
      description: "Soft idlis topped with ghee",
      price: 35,
      isVeg: true,
      image: "/images/food/ghee-idly.jpg",
    },
    {
      id: "5",
      name: "Button Idly Sambar",
      description: "Small button idlis soaked in sambar",
      price: 70,
      isVeg: true,
      isPopular: true,
      image: "/images/food/button-idly-sambar.jpg",
    },
    {
      id: "6",
      name: "Ghee Button Idly Sambar",
      description: "Button idlis in sambar with ghee",
      price: 80,
      isVeg: true,
      image: "/images/food/ghee-button-idly-sambar.jpg",
    },
    {
      id: "7",
      name: "Mini Idly 2 No's",
      description: "2 pieces of mini idlis",
      price: 40,
      isVeg: true,
      image: "/images/food/mini-idly.jpg",
    },
    {
      id: "8",
      name: "Idly & Vada",
      description: "Combination of idly and vada",
      price: 65,
      isVeg: true,
      isPopular: true,
      image: "/images/food/idly-vada.jpg",
    },
    {
      id: "9",
      name: "Rava Idly",
      description: "Semolina idlis served with sambar and chutney",
      price: 60,
      isVeg: true,
      image: "/images/food/rava-idly.jpg",
    },
    {
      id: "10",
      name: "Ghee Rava Idly",
      description: "Rava idlis topped with ghee",
      price: 55,
      isVeg: true,
      image: "/images/food/ghee-rava-idly.jpg",
    },
  ],
  dosa: [
    {
      id: "11",
      name: "Masala Dosa",
      description: "Crispy rice crepe filled with spiced potato masala",
      price: 75,
      isVeg: true,
      isPopular: true,
      image: "/images/food/masala-dosa.jpg",
    },
    {
      id: "12",
      name: "Ghee Masala Dosa",
      description: "Masala dosa roasted with ghee",
      price: 85,
      isVeg: true,
      isPopular: true,
      image: "/images/food/ghee-masala-dosa.jpg",
    },
    {
      id: "13",
      name: "Ghee Kaju Dosa",
      description: "Dosa roasted in ghee with cashew nuts",
      price: 110,
      isVeg: true,
      image: "/images/food/ghee-kaju-dosa.jpg",
    },
    {
      id: "14",
      name: "Ghee Pudi Masala Dosa",
      description: "Masala dosa with ghee and podi spice mix",
      price: 95,
      isVeg: true,
      image: "/images/food/ghee-pudi-masala-dosa.jpg",
    },
    {
      id: "15",
      name: "Set Dosa",
      description: "Set of 3 soft spongy dosas",
      price: 70,
      isVeg: true,
      isPopular: true,
      image: "/images/food/set-dosa.jpg",
    },
    {
      id: "16",
      name: "Plain Dosa",
      description: "Thin and crispy rice crepe",
      price: 60,
      isVeg: true,
      image: "/images/food/plain-dosa.jpg",
    },
    {
      id: "17",
      name: "Ghee Pudi Plain Dosa",
      description: "Plain dosa with ghee and podi",
      price: 75,
      isVeg: true,
      image: "/images/food/ghee-pudi-plain-dosa.jpg",
    },
    {
      id: "18",
      name: "Butter Masala Dosa",
      description: "Masala dosa roasted with butter",
      price: 85,
      isVeg: true,
      image: "/images/food/butter-masala-dosa.jpg",
    },
    {
      id: "19",
      name: "Butter Open Dosa",
      description: "Open dosa roasted with butter",
      price: 80,
      isVeg: true,
      image: "/images/food/butter-open-dosa.jpg",
    },
    {
      id: "20",
      name: "Onion Dosa",
      description: "Dosa topped with onions",
      price: 70,
      isVeg: true,
      image: "/images/food/onion-dosa.jpg",
    },
    {
      id: "21",
      name: "Ghee Ragi Dosa",
      description: "Healthy ragi dosa roasted in ghee",
      price: 75,
      isVeg: true,
      image: "/images/food/ghee-ragi-dosa.jpg",
    },
    {
      id: "22",
      name: "Sagu Dosa",
      description: "Dosa filled with vegetable sagu",
      price: 60,
      isVeg: true,
      image: "/images/food/sagu-dosa.jpg",
    },
    {
      id: "23",
      name: "Puri Sagu",
      description: "Puffed puris served with vegetable sagu",
      price: 65,
      isVeg: true,
      image: "/images/food/puri-sagu.jpg",
    },
  ],
  chinese: [
    {
      id: "24",
      name: "Gobi Manchurian",
      description: "Crispy cauliflower florets in spicy Indo-Chinese sauce",
      price: 109,
      isVeg: true,
      isPopular: true,
      image: "/images/food/gobi-manchurian.jpg",
    },
    {
      id: "25",
      name: "Mushroom Manchurian",
      description: "Mushrooms in spicy manchurian sauce",
      price: 139,
      isVeg: true,
      image: "/images/food/mushroom-manchurian.jpg",
    },
    {
      id: "26",
      name: "Paneer Manchurian",
      description: "Cottage cheese in manchurian sauce",
      price: 149,
      isVeg: true,
      isPopular: true,
      image: "/images/food/paneer-manchurian.jpg",
    },
    {
      id: "27",
      name: "Baby Corn Manchurian",
      description: "Baby corn in spicy manchurian gravy",
      price: 129,
      isVeg: true,
      image: "/images/food/baby-corn-manchurian.jpg",
    },
    {
      id: "28",
      name: "Chilli Paneer",
      description: "Paneer cubes tossed in spicy chilli sauce",
      price: 159,
      isVeg: true,
      isPopular: true,
      image: "/images/food/chilli-paneer.jpg",
    },
    {
      id: "29",
      name: "Mushroom Chilli",
      description: "Mushrooms in spicy chilli sauce",
      price: 149,
      isVeg: true,
      image: "/images/food/mushroom-chilli.jpg",
    },
    {
      id: "30",
      name: "Gobi Chilli",
      description: "Cauliflower in chilli sauce",
      price: 119,
      isVeg: true,
      image: "/images/food/gobi-chilli.jpg",
    },
    {
      id: "31",
      name: "Baby Corn Chilli",
      description: "Baby corn in spicy chilli preparation",
      price: 139,
      isVeg: true,
      image: "/images/food/baby-corn-chilli.jpg",
    },
    {
      id: "32",
      name: "Veg Fried Rice",
      description: "Classic vegetable fried rice",
      price: 109,
      isVeg: true,
      image: "/images/food/veg-fried-rice.jpg",
    },
    {
      id: "33",
      name: "Paneer Fried Rice",
      description: "Fried rice with paneer cubes",
      price: 139,
      isVeg: true,
      isPopular: true,
      image: "/images/food/paneer-fried-rice.jpg",
    },
    {
      id: "34",
      name: "Mushroom Fried Rice",
      description: "Fried rice with mushrooms",
      price: 129,
      isVeg: true,
      image: "/images/food/mushroom-fried-rice.jpg",
    },
    {
      id: "35",
      name: "Baby Corn Fried Rice",
      description: "Fried rice with baby corn",
      price: 119,
      isVeg: true,
      image: "/images/food/baby-corn-fried-rice.jpg",
    },
    {
      id: "36",
      name: "Veg Noodles",
      description: "Classic vegetable noodles",
      price: 109,
      isVeg: true,
      image: "/images/food/veg-noodles.jpg",
    },
    {
      id: "37",
      name: "Veg Hakka Noodles",
      description: "Hakka style vegetable noodles",
      price: 119,
      isVeg: true,
      isPopular: true,
      image: "/images/food/veg-hakka-noodles.jpg",
    },
    {
      id: "38",
      name: "Paneer Noodles",
      description: "Noodles with paneer",
      price: 139,
      isVeg: true,
      image: "/images/food/paneer-noodles.jpg",
    },
    {
      id: "39",
      name: "Mushroom Noodles",
      description: "Noodles with mushrooms",
      price: 129,
      isVeg: true,
      image: "/images/food/mushroom-noodles.jpg",
    },
    {
      id: "40",
      name: "Baby Corn Noodles",
      description: "Noodles with baby corn",
      price: 119,
      isVeg: true,
      image: "/images/food/baby-corn-noodles.jpg",
    },
    {
      id: "41",
      name: "Paneer Ghee Roast",
      description: "Paneer in spicy ghee roast masala",
      price: 159,
      isVeg: true,
      isPopular: true,
      image: "/images/food/paneer-ghee-roast.jpg",
    },
    {
      id: "42",
      name: "Paneer Pepper Dry",
      description: "Dry paneer with black pepper",
      price: 149,
      isVeg: true,
      image: "/images/food/paneer-pepper-dry.jpg",
    },
    {
      id: "43",
      name: "Mushroom Pepper Dry",
      description: "Dry mushroom preparation with black pepper",
      price: 149,
      isVeg: true,
      image: "/images/food/mushroom-pepper-dry.jpg",
    },
  ],
  beverages: [
    {
      id: "44",
      name: "Tea",
      description: "Hot tea",
      price: 20,
      isVeg: true,
      image: "/images/food/tea.jpg",
    },
    {
      id: "45",
      name: "Coffee",
      description: "Hot coffee",
      price: 20,
      isVeg: true,
      isPopular: true,
      image: "/images/food/coffee.jpg",
    },
    {
      id: "46",
      name: "Black Coffee",
      description: "Black coffee without milk",
      price: 20,
      isVeg: true,
      image: "/images/food/black-coffee.jpg",
    },
    {
      id: "47",
      name: "Lemon Tea",
      description: "Refreshing tea with lemon",
      price: 20,
      isVeg: true,
      image: "/images/food/lemon-tea.jpg",
    },
    {
      id: "48",
      name: "Badam Milk",
      description: "Almond flavored milk",
      price: 25,
      isVeg: true,
      isPopular: true,
      image: "/images/food/badam-milk.jpg",
    },
  ],
};

export const FEATURES = [
  {
    title: "Fast Service",
    description: "Quick preparation and serving without compromising quality",
    icon: "Zap",
  },
  {
    title: "Authentic Taste",
    description: "Traditional recipes passed down through generations",
    icon: "Sparkles",
  },
  {
    title: "Affordable Pricing",
    description: "Delicious meals starting from just ₹1 per person",
    icon: "IndianRupee",
  },
  {
    title: "Family Friendly",
    description: "Welcoming atmosphere perfect for families and groups",
    icon: "Users",
  },
];

export const REVIEWS = [
  {
    id: "1",
    author: "Rajesh Kumar",
    rating: 5,
    date: "2 weeks ago",
    text: "Best dosas in Jayanagar! The ghee podi idly is my favorite. Great taste and very affordable.",
    avatar: "RK",
  },
  {
    id: "2",
    author: "Priya Sharma",
    rating: 4,
    date: "1 month ago",
    text: "Authentic South Indian food. The filter coffee is excellent. Quick service and clean ambiance.",
    avatar: "PS",
  },
  {
    id: "3",
    author: "Arun Reddy",
    rating: 5,
    date: "3 weeks ago",
    text: "Family favorite spot for breakfast. Bisi bele bath is amazing. Highly recommend!",
    avatar: "AR",
  },
];

export const NAVIGATION = [
  { name: "Home", href: "/" },
  { name: "Menu", href: "/menu" },
  { name: "About", href: "/about" },
  { name: "Reviews", href: "/reviews" },
  { name: "Contact", href: "/contact" },
];
